[package]
name = "mandelbrot-set"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
rayon = "1.10.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html